#!/bin/bash
#
##
# Advanced Policy Firewall (APF) v1.7.5
#             (C) 2002-2014, R-fx Networks <proj@rfxn.com>
#             (C) 2014, Ryan MacDonald <ryan@rfxn.com>
# This program may be freely redistributed under the terms of the GNU GPL v2
##
#
INSTALL_PATH="/etc/apf"
DEF=".ca.def"
DOUT=".conf.apf"

if [ -d "/etc/apf.bk.last" ]; then
# get all the vars from current release
. /etc/apf/conf.apf
NEW_SYSCTL_CONNTRACK="$SYSCTL_CONNTRACK"
# replace with any vars old release had
. /etc/apf.bk.last/conf.apf
# make sure conntrack is set and is not lower than package default
if [ -z "$SYSCTL_CONNTRACK" ] || [ -z "$NEW_SYSCTL_CONNTRACK" ]; then
	SYSCTL_CONNTRACK="131072"
elif [ "$NEW_SYSCTL_CONNTRACK" -lt "$SYSCTL_CONNTRACK" ]; then
	SYSCTL_CONNTRACK="131072"
fi
# generate new conf
. $DEF

cp -f $INSTALL_PATH/conf.apf $INSTALL_PATH/conf.apf.orig
cp -f $DOUT $INSTALL_PATH/conf.apf
cp -f /etc/apf.bk.last/*_hosts.rules /etc/apf/
cp -f /etc/apf.bk.last/vnet/*.rules /etc/apf/vnet/

OV=`cat /etc/apf.bk.last/VERSION | awk '{print$2}'`
NV=`cat /etc/apf/VERSION | awk '{print$2}'`
        echo "  Imported options from $OV to $NV."
fi
