#!/bin/bash
#
# apf Package Install Verification Tests
# Generated by pkg_gen.sh from pkg_lib templates
#
# Run inside Docker containers after package installation.
# Verifies FHS file layout, symlink farm, permissions, and basic execution.
#
# Usage: test-pkg-install.sh [rpm|deb]
#
# Placeholders:
#   apf            — package name
#   2.0.2         — version string for execution test
#   apf        — binary name in /usr/sbin
#   /usr/local/sbin/fwmgr      — legacy binary path
#   /etc/apf    — legacy install path
#   8         — man page section
#   (fhs files)     — check_file calls for FHS file layout
#   (symlinks)      — check_link calls for symlink farm
#   (extra tests)   — project-specific verification tests (optional)
#
set -euo pipefail

PASS=0
FAIL=0
PKG_TYPE="${1:-auto}"

pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

check_file() {
	local path="$1" desc="$2"
	if [ -f "$path" ] || [ -d "$path" ]; then
		pass "$desc ($path)"
	else
		fail "$desc ($path missing)"
	fi
}

check_link() {
	local link="$1" target="$2" desc="$3"
	if [ -L "$link" ]; then
		local actual actual_resolved target_resolved
		actual=$(readlink "$link")
		# DEB uses relative symlinks (e.g., ../../sbin/apf); resolve both to absolute for comparison
		actual_resolved=$(readlink -f "$link" 2>/dev/null || echo "$actual")
		target_resolved=$(readlink -f "$target" 2>/dev/null || echo "$target")
		if [ "$actual" = "$target" ] || [ "$actual_resolved" = "$target_resolved" ]; then
			pass "$desc ($link -> $actual)"
		else
			fail "$desc ($link -> $actual, expected $target)"
		fi
	else
		fail "$desc ($link is not a symlink)"
	fi
}

check_perms() {
	local path="$1" expected="$2" desc="$3"
	if [ -e "$path" ]; then
		local actual
		actual=$(stat -c '%a' "$path")
		if [ "$actual" = "$expected" ]; then
			pass "$desc (perms $actual)"
		else
			fail "$desc (perms $actual, expected $expected)"
		fi
	else
		fail "$desc ($path missing)"
	fi
}

# Auto-detect package type
if [ "$PKG_TYPE" = "auto" ]; then
	if command -v rpm >/dev/null 2>&1 && rpm -q apf >/dev/null 2>&1; then
		PKG_TYPE="rpm"
	elif command -v dpkg >/dev/null 2>&1 && dpkg -s apf >/dev/null 2>&1; then
		PKG_TYPE="deb"
	else
		echo "ERROR: Cannot detect installed package type"
		exit 1
	fi
fi

echo "=== apf Package Verification ($PKG_TYPE) ==="
echo ""

# --- Test 1: FHS paths exist ---
echo "--- Test 1: FHS file layout ---"
check_file /usr/sbin/apf "Executable"
check_file /etc/apf/conf.apf "Config: conf.apf"
check_file /etc/apf/internals/internals.conf "Config: internals.conf"
check_file /etc/apf/allow_hosts.rules "Config: allow_hosts.rules"
check_file /etc/apf/deny_hosts.rules "Config: deny_hosts.rules"
check_file /usr/lib/apf/internals/apf.lib.sh "Library: apf.lib.sh"
check_file /usr/lib/apf/internals/apf_core.sh "Library: apf_core.sh"
check_file /usr/lib/apf/internals/pkg_lib.sh "Library: pkg_lib.sh"
check_file /usr/lib/apf/extras/importconf "Executable: importconf"
check_file /usr/lib/apf/extras/get_ports "Executable: get_ports"
check_file /usr/lib/apf/vnet/vnetgen "Executable: vnetgen"
check_file /usr/lib/apf/internals/.symlink-manifest "Manifest: .symlink-manifest"
check_file /etc/apf/vnet/main.vnet "Template: main.vnet"
check_file /etc/cron.d/apf "System: cron"
check_file /etc/logrotate.d/apf "System: logrotate"
check_file /usr/share/bash-completion/completions/apf "System: bash-completion"
check_file /usr/share/doc/apf/README* "Doc: README"
check_file /var/lib/apf/tmp "State: tmp dir"
check_file /var/log/apf "State: log dir"
echo ""

# --- Test 2: Symlink farm ---
echo "--- Test 2: Symlink farm ---"
check_link /etc/apf/internals/apf.lib.sh /usr/lib/apf/internals/apf.lib.sh "Symlink: apf.lib.sh"
check_link /etc/apf/internals/apf_core.sh /usr/lib/apf/internals/apf_core.sh "Symlink: apf_core.sh"
check_link /etc/apf/internals/apf_trust.sh /usr/lib/apf/internals/apf_trust.sh "Symlink: apf_trust.sh"
check_link /etc/apf/internals/pkg_lib.sh /usr/lib/apf/internals/pkg_lib.sh "Symlink: pkg_lib.sh"
check_link /etc/apf/internals/cports.common /usr/lib/apf/internals/cports.common "Symlink: cports.common"
check_link /etc/apf/extras /usr/lib/apf/extras "Symlink: extras dir"
check_link /etc/apf/doc /usr/share/doc/apf "Symlink: doc dir"
check_link /etc/apf/vnet/vnetgen /usr/lib/apf/vnet/vnetgen "Symlink: vnetgen"
check_link /usr/local/sbin/apf /usr/sbin/apf "Symlink: /usr/local/sbin/apf"
check_link /usr/local/sbin/fwmgr /usr/sbin/apf "Symlink: /usr/local/sbin/fwmgr"
echo ""

# --- Test 3: Permissions ---
echo "--- Test 3: File permissions ---"
check_perms /usr/sbin/apf 755 "Executable perms"
echo ""

# --- Test 4: Man page ---
echo "--- Test 4: Man page ---"
check_file /usr/share/man/man8/apf.8* "Man page"
echo ""

# --- Test: Conffile count ---
echo "--- Test: Conffile list ---"
if [ "$PKG_TYPE" = "rpm" ]; then
    confcount=$(rpm -qc apf 2>/dev/null | wc -l)
    # RPM: exactly 11 conffiles (from %config(noreplace))
    if [ "$confcount" -eq 11 ]; then
        pass "Conffile count ($confcount)"
    else
        fail "Conffile count ($confcount, expected 11)"
    fi
else
    confcount=$(grep -c '^/' /var/lib/dpkg/info/apf.conffiles 2>/dev/null || echo 0)
    # DEB: exactly 11 conffiles (explicit list via debian/apf.conffiles)
    if [ "$confcount" -eq 11 ]; then
        pass "Conffile count ($confcount)"
    else
        fail "Conffile count ($confcount, expected 11)"
    fi
fi
echo ""

# --- Test: Symlink manifest ---
echo "--- Test: Symlink manifest ---"
manifest="/usr/lib/apf/internals/.symlink-manifest"
if [ -f "$manifest" ]; then
    mcount=$(grep -c $'\t' "$manifest")
    if [ "$mcount" -ge 20 ]; then
        pass "Manifest entries ($mcount)"
    else
        fail "Manifest entries ($mcount, expected >= 20)"
    fi
else
    fail "Manifest file missing ($manifest)"
fi
echo ""

# --- Test: Service unit ---
echo "--- Test: Service unit ---"
if [ "$PKG_TYPE" = "rpm" ]; then
    check_file /usr/lib/systemd/system/apf.service "systemd unit (RPM)"
else
    check_file /lib/systemd/system/apf.service "systemd unit (DEB)"
fi
echo ""

# --- Test: Execution ---
echo "--- Test: apf execution ---"
ver_out=$(/usr/local/sbin/fwmgr --version 2>&1 || true)
if echo "$ver_out" | grep -q '2.0.2'; then
	pass "apf --version via /usr/local/sbin/fwmgr works"
else
	fail "apf --version output: $ver_out"
fi
ver_out2=$(/usr/sbin/apf --version 2>&1 || true)
if echo "$ver_out2" | grep -q '2.0.2'; then
	pass "apf --version via /usr/sbin/apf works"
else
	fail "apf --version via /usr/sbin/apf output: $ver_out2"
fi
echo ""

# --- Summary ---
echo "=== Results: $PASS passed, $FAIL failed ==="
if [ "$FAIL" -gt 0 ]; then
	exit 1
fi
exit 0
