#!/bin/bash
#
# apf Package Install Verification Tests
# Generated by pkg_gen.sh from pkg_lib templates
#
# Run inside Docker containers after package installation.
# Verifies FHS file layout, symlink farm, permissions, and basic execution.
#
# Usage: test-pkg-install.sh [rpm|deb]
#
# Placeholders:
#   apf            — package name
#   2.0.2         — version string for execution test
#   apf        — binary name in /usr/sbin
#   /usr/local/sbin/fwmgr      — legacy binary path
#   /etc/apf    — legacy install path
#   8         — man page section
#   @@PKG_TEST_FHS_FILES@@  — check_file calls for FHS file layout
#   @@PKG_TEST_SYMLINKS@@   — check_link calls for symlink farm
#   @@PKG_TEST_EXTRA@@      — project-specific verification tests (optional)
#
set -euo pipefail

PASS=0
FAIL=0
PKG_TYPE="${1:-auto}"

pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

check_file() {
	local path="$1" desc="$2"
	if [ -f "$path" ] || [ -d "$path" ]; then
		pass "$desc ($path)"
	else
		fail "$desc ($path missing)"
	fi
}

check_link() {
	local link="$1" target="$2" desc="$3"
	if [ -L "$link" ]; then
		local actual
		actual=$(readlink "$link")
		if [ "$actual" = "$target" ]; then
			pass "$desc ($link -> $target)"
		else
			fail "$desc ($link -> $actual, expected $target)"
		fi
	else
		fail "$desc ($link is not a symlink)"
	fi
}

check_perms() {
	local path="$1" expected="$2" desc="$3"
	if [ -e "$path" ]; then
		local actual
		actual=$(stat -c '%a' "$path")
		if [ "$actual" = "$expected" ]; then
			pass "$desc (perms $actual)"
		else
			fail "$desc (perms $actual, expected $expected)"
		fi
	else
		fail "$desc ($path missing)"
	fi
}

# Auto-detect package type
if [ "$PKG_TYPE" = "auto" ]; then
	if command -v rpm >/dev/null 2>&1 && rpm -q apf >/dev/null 2>&1; then
		PKG_TYPE="rpm"
	elif command -v dpkg >/dev/null 2>&1 && dpkg -s apf >/dev/null 2>&1; then
		PKG_TYPE="deb"
	else
		echo "ERROR: Cannot detect installed package type"
		exit 1
	fi
fi

echo "=== apf Package Verification ($PKG_TYPE) ==="
echo ""

# --- Test 1: FHS paths exist ---
echo "--- Test 1: FHS file layout ---"
check_file /usr/sbin/apf "Executable"
@@PKG_TEST_FHS_FILES@@
echo ""

# --- Test 2: Symlink farm ---
echo "--- Test 2: Symlink farm ---"
@@PKG_TEST_SYMLINKS@@
check_link /usr/local/sbin/fwmgr /usr/sbin/apf "Symlink: /usr/local/sbin/fwmgr"
echo ""

# --- Test 3: Permissions ---
echo "--- Test 3: File permissions ---"
check_perms /usr/sbin/apf 755 "Executable perms"
echo ""

# --- Test 4: Man page ---
echo "--- Test 4: Man page ---"
check_file /usr/share/man/man8/apf.8* "Man page"
echo ""

@@PKG_TEST_EXTRA@@

# --- Test: Execution ---
echo "--- Test: apf execution ---"
ver_out=$(/usr/local/sbin/fwmgr --version 2>&1 || true)
if echo "$ver_out" | grep -q '2.0.2'; then
	pass "apf --version via /usr/local/sbin/fwmgr works"
else
	fail "apf --version output: $ver_out"
fi
ver_out2=$(/usr/sbin/apf --version 2>&1 || true)
if echo "$ver_out2" | grep -q '2.0.2'; then
	pass "apf --version via /usr/sbin/apf works"
else
	fail "apf --version via /usr/sbin/apf output: $ver_out2"
fi
echo ""

# --- Summary ---
echo "=== Results: $PASS passed, $FAIL failed ==="
if [ "$FAIL" -gt 0 ]; then
	exit 1
fi
exit 0
