# apf RPM spec — generated by pkg_gen.sh from pkg_lib templates
#
# Placeholders (substituted by pkg_gen.sh from project manifest):
#   apf             — package name (e.g., bfd, apf, maldet)
#   2.0.2          — version string (e.g., 2.0.1)
#   Advanced Policy Firewall — iptables/netfilter firewall management          — one-line package summary
#   Advanced Policy Firewall (APF) is an iptables/netfilter-based firewall management system for Linux servers. It provides stateful packet filtering, trust-based allow/deny host management, Reactive Address Blocking (RAB), and a Virtual Network (VNET) subsystem for per-IP policies.      — multi-line package description
#   GPLv2+           — license identifier (e.g., GPLv2+)
#   https://github.com/rfxn/advanced-policy-firewall              — upstream URL
#   R-fx Networks <proj@rfxn.com>       — maintainer name + email
#   /etc/apf     — legacy install path (e.g., /usr/local/bfd)
#   apf         — binary name in /usr/sbin
#   /usr/local/sbin/fwmgr       — legacy binary path (e.g., /usr/local/sbin/bfd)
#   8          — man page section (e.g., 1, 8)
#   2002  — copyright start year (e.g., 1999, 2002)
#   @@PKG_RPM_REQUIRES@@     — Requires: lines (one per line)
#   @@PKG_RPM_WEAK_DEPS@@    — Recommends/Suggests lines (conditional on el8+)
#   @@PKG_RPM_BUILD_SECTION@@     — %build section commands
#   @@PKG_RPM_INSTALL_SECTION@@   — %install section commands
#   @@PKG_RPM_PRE_SECTION@@       — %pre scriptlet body
#   @@PKG_RPM_POST_SECTION@@      — %post scriptlet body
#   @@PKG_RPM_PREUN_SECTION@@     — %preun scriptlet body
#   @@PKG_RPM_POSTUN_SECTION@@    — %postun scriptlet body
#   @@PKG_RPM_FILES_SECTION@@     — %files listing
#   @@PKG_RPM_CHANGELOG@@         — %changelog entries
#
%define name    apf
%define version 2.0.2
%define release 1%{?dist}

# Legacy install path used by install.sh — symlink farm target
%define legacy_path /etc/apf

Name:           %{name}
Version:        %{version}
Release:        %{release}
Summary:        Advanced Policy Firewall — iptables/netfilter firewall management
License:        GPLv2+
URL:            https://github.com/rfxn/advanced-policy-firewall
Source0:        %{name}-%{version}.tar.gz
BuildArch:      noarch

@@PKG_RPM_REQUIRES@@
@@PKG_RPM_WEAK_DEPS@@

%description
Advanced Policy Firewall (APF) is an iptables/netfilter-based firewall management system for Linux servers. It provides stateful packet filtering, trust-based allow/deny host management, Reactive Address Blocking (RAB), and a Virtual Network (VNET) subsystem for per-IP policies.

%prep
%setup -q -n %{name}-%{version}

%build
@@PKG_RPM_BUILD_SECTION@@

%install
rm -rf %{buildroot}
@@PKG_RPM_INSTALL_SECTION@@

%pre
@@PKG_RPM_PRE_SECTION@@

%post
@@PKG_RPM_POST_SECTION@@

%preun
@@PKG_RPM_PREUN_SECTION@@

%postun
@@PKG_RPM_POSTUN_SECTION@@

%files
%license COPYING.GPL
@@PKG_RPM_FILES_SECTION@@

%changelog
@@PKG_RPM_CHANGELOG@@
