name: APF Smoke Tests

on:
  push:
    branches: [master, '2.*']
  pull_request:
    branches: [master]

jobs:
  smoke-test:
    uses: rfxn/batsman/.github/workflows/test.yml@v1.0.3
    with:
      project-name: apf
      os-matrix: '["debian12","centos6","centos7","rocky8","rocky9","ubuntu1204","ubuntu2004","ubuntu2404"]'
      docker-run-flags: '--privileged'
